### ISSUE TITLE
Plublishing on NPM

### ISSUE THREAD

**Issue by StanCallewaert** [transferwise/currency-flags#1]
Hello,

I was wondering if you could publish this repo on npm. That way you don't have to include the whole Github URL in the package.json anymore (way more clean).

Thanks in advance!

**Comment by AdriVanHoudt** [comment]
Since this seemed pretty unmaintained we released a version on npm https://www.npmjs.com/package/currency-flags

**Comment by AdriVanHoudt** [comment]
@oliverviljamaa I would have no problem merging our fork with this main project btw

**Comment by oliverviljamaa** [comment]
@AdriVanHoudt Agreed!

**Comment by AdriVanHoudt** [comment]
@oliverviljamaa I would suggest you take a look at what I did on our fork and see what can be incorporated into this repo (mostly version updates) 
Then we incorporate the changes and I'll add you to the npm package users so you can publish new versions on npm

**Comment by oliverviljamaa** [comment]
@AdriVanHoudt I read through the commits and we could take from your contributions the EGP flag from 601cdefab22ccb62d6fb5c68c94a2f9062ebdd9d, and removing `npm start` and updating versions and changing scripts accordingly from bcf1c10e98acc0384a8ef6382411937d041a6967.

What do you think would be a good process for doing this?

**Comment by AdriVanHoudt** [comment]
I can do PR's or you can add the fork as a remote and cherry pick the commits, not sure how this is done normally :P

**Comment by oliverviljamaa** [comment]
Let's do the PR-s, more collaborative.

**Comment by gusso** [comment]
This was handled a while ago, package is already on npm.
